'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.261
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace RTIService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="RTIService.IRTIAutoConfirmationService")>  _
    Public Interface IRTIAutoConfirmationService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IRTIAutoConfirmationService/IsWithinMargin", ReplyAction:="http://tempuri.org/IRTIAutoConfirmationService/IsWithinMarginResponse")>  _
        Function IsWithinMargin(ByVal DestinationCode As String, ByVal ArticleCode As String, ByVal StarDate As Date, ByVal EndDate As Date, ByVal BookingNumber As String, ByVal Age As Integer, ByVal SalesOfficeCode As String) As Boolean
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IRTIAutoConfirmationServiceChannel
        Inherits RTIService.IRTIAutoConfirmationService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class RTIAutoConfirmationServiceClient
        Inherits System.ServiceModel.ClientBase(Of RTIService.IRTIAutoConfirmationService)
        Implements RTIService.IRTIAutoConfirmationService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function IsWithinMargin(ByVal DestinationCode As String, ByVal ArticleCode As String, ByVal StarDate As Date, ByVal EndDate As Date, ByVal BookingNumber As String, ByVal Age As Integer, ByVal SalesOfficeCode As String) As Boolean Implements RTIService.IRTIAutoConfirmationService.IsWithinMargin
            Return MyBase.Channel.IsWithinMargin(DestinationCode, ArticleCode, StarDate, EndDate, BookingNumber, Age, SalesOfficeCode)
        End Function
    End Class
End Namespace
