Imports System.Data.SqlClient

Namespace Sprocs
    Friend Class asp_LSUpdateTrackerInsert
        Inherits DataH.EFSqlCommand
        'Builds command for sproc asp_RemoveInpBookings
        'Generated by the code spewer on 5/16/2007 5:40:57 PM
        Dim _params As New ParametersClass(Me.SqlCmd)

        Public Sub New()
            MyBase.New()
            Dim p As SqlParameter
            Me.SqlCmd.CommandText = "asp_LSUpdateTrackerInsert"
            Me.SqlCmd.CommandType = System.Data.CommandType.StoredProcedure

            With Me.SqlCmd.Parameters
                p = .Add(New SqlParameter("@RETURN_VALUE", SqlDbType.Int, 0)) '
                p.Direction = ParameterDirection.ReturnValue  'special direction
                p = .Add(New SqlParameter("@salesBookingId", SqlDbType.VarChar, 8000)) '
                p = .Add(New SqlParameter("@RequiredItem_id", SqlDbType.Char, 10)) '
            End With

        End Sub

        Friend ReadOnly Property Parameters() As ParametersClass
            Get
                Return _params
            End Get
        End Property

        Friend Class ParametersClass
            Dim _sqlCmd As New SqlCommand

            Friend Sub New(ByVal cmd As SqlCommand)
                _sqlCmd = cmd
            End Sub

            Property RETURN_VALUE() As Integer
                Get
                    Return CType(_sqlCmd.Parameters("@RETURN_VALUE").Value, Integer)
                End Get

                Set(ByVal Value As Integer)
                    _sqlCmd.Parameters("@RETURN_VALUE").Value = Value
                End Set
            End Property

            Property salesBookingId() As String
                Get
                    Return CType(_sqlCmd.Parameters("@salesBookingId").Value, String)
                End Get

                Set(ByVal Value As String)
                    _sqlCmd.Parameters("@salesBookingId").Value = Value
                End Set
            End Property

            Property RequiredItem_id() As Integer
                Get
                    Return CType(_sqlCmd.Parameters("@RequiredItem_id").Value, Integer)
                End Get

                Set(ByVal Value As Integer)
                    _sqlCmd.Parameters("@RequiredItem_id").Value = Value
                End Set
            End Property

        End Class

    End Class
End Namespace

