Imports System.Data.SqlClient

Namespace Sprocs
    Friend Class asp_CourseFindByCourseTypeCode
        Inherits DataH.EFSqlCommand
        'Builds command for sproc asp_CourseFindByCourseTypeCode
        'Generated by the code spewer on 1/31/2007 9:49:55 PM
        Dim _params As New ParametersClass(Me.SqlCmd)

        Public Sub New()
            MyBase.New()
            Dim p As SqlParameter
            Me.SqlCmd.CommandText = "asp_CourseFindByCourseTypeCode"
            Me.SqlCmd.CommandType = System.Data.CommandType.StoredProcedure

            With Me.SqlCmd.Parameters
                p = .Add(New SqlParameter("@RETURN_VALUE", SqlDbType.Int, 0))  '
                p.Direction = ParameterDirection.ReturnValue  'special direction
                p = .Add(New SqlParameter("@DestinationCode", SqlDbType.VarChar, 20))  '
                p = .Add(New SqlParameter("@ProgramCode", SqlDbType.VarChar, 20))  '
                p = .Add(New SqlParameter("@CourseNumber", SqlDbType.VarChar, 20))  '
                p = .Add(New SqlParameter("@salesOfficeCode", SqlDbType.VarChar, 20))  '
                p = .Add(New SqlParameter("@Course_id", SqlDbType.Int, 0))  '
                p.Direction = ParameterDirection.InputOutput  'special direction
            End With

        End Sub

        Friend ReadOnly Property Parameters() As ParametersClass
            Get
                Return _params
            End Get
        End Property

        Friend Class ParametersClass
            Dim _sqlCmd As New SqlCommand()

            Friend Sub New(ByVal cmd As SqlCommand)
                _sqlCmd = cmd
            End Sub

            Property RETURN_VALUE() As Integer
                Get
                    Return CType(_sqlCmd.Parameters("@RETURN_VALUE").Value, Integer)
                End Get

                Set(ByVal Value As Integer)
                    _sqlCmd.Parameters("@RETURN_VALUE").Value = Value
                End Set
            End Property

            Property DestinationCode() As String
                Get
                    Return CType(_sqlCmd.Parameters("@DestinationCode").Value, String)
                End Get

                Set(ByVal Value As String)
                    _sqlCmd.Parameters("@DestinationCode").Value = Value
                End Set
            End Property

            Property ProgramCode() As String
                Get
                    Return CType(_sqlCmd.Parameters("@ProgramCode").Value, String)
                End Get

                Set(ByVal Value As String)
                    _sqlCmd.Parameters("@ProgramCode").Value = Value
                End Set
            End Property

            Property CourseNumber() As String
                Get
                    Return CType(_sqlCmd.Parameters("@CourseNumber").Value, String)
                End Get

                Set(ByVal Value As String)
                    _sqlCmd.Parameters("@CourseNumber").Value = Value
                End Set
            End Property

            Property salesOfficeCode() As String
                Get
                    Return CType(_sqlCmd.Parameters("@salesOfficeCode").Value, String)
                End Get

                Set(ByVal Value As String)
                    _sqlCmd.Parameters("@salesOfficeCode").Value = Value
                End Set
            End Property

            Property Course_id() As Integer
                Get
                    Return CType(_sqlCmd.Parameters("@Course_id").Value, Integer)
                End Get

                Set(ByVal Value As Integer)
                    _sqlCmd.Parameters("@Course_id").Value = Value
                End Set
            End Property

        End Class

    End Class
End Namespace

