Imports System.Data.SqlClient
Public Class asp_FlightItinFindBySalesFlightItinId
    Inherits DataH.EFSqlCommand
    'Builds command for sproc asp_FlightItinFindBySalesFlightItinId
    'Generated by the code spewer on 7/12/2004 5:17:14 PM
    Dim _params As New ParametersClass(Me.SqlCmd)

    Public Sub New()
        MyBase.New()
        Dim p As SqlParameter
        Me.SqlCmd.CommandText = "asp_FlightItinFindBySalesFlightItinId"
        Me.SqlCmd.CommandType = System.Data.CommandType.StoredProcedure

        With Me.SqlCmd.Parameters
            p = .Add(New SqlParameter("@RETURN_VALUE", SqlDbType.Int, 0)) '
            p.Direction = ParameterDirection.ReturnValue  'special direction
            p = .Add(New SqlParameter("@SalesFlightItinId", SqlDbType.VarChar, 20)) '
            p = .Add(New SqlParameter("@FlightItin_id", SqlDbType.Int, 0)) '
            p.Direction = ParameterDirection.InputOutput  'special direction
        End With

    End Sub

    Friend ReadOnly Property Parameters() As ParametersClass
        Get
            Return _params
        End Get
    End Property

    Friend Class ParametersClass
        Dim _sqlCmd As New SqlCommand

        Friend Sub New(ByVal cmd As SqlCommand)
            _sqlCmd = cmd
        End Sub

        Property RETURN_VALUE() As Integer
            Get
                Return CType(_sqlCmd.Parameters("@RETURN_VALUE").Value, Integer)
            End Get
            Set(ByVal Value As Integer)
                _sqlCmd.Parameters("@RETURN_VALUE").Value = Value
            End Set
        End Property

        Property SalesFlightItinId() As String
            Get
                Return CType(_sqlCmd.Parameters("@SalesFlightItinId").Value, String)
            End Get
            Set(ByVal Value As String)
                _sqlCmd.Parameters("@SalesFlightItinId").Value = Value
            End Set
        End Property

        Property FlightItin_id() As Integer
            Get
                Return CInt(Null.ReplaceNull(_sqlCmd.Parameters("@FlightItin_id").Value, Null.IntegerNull))
            End Get
            Set(ByVal Value As Integer)
                _sqlCmd.Parameters("@FlightItin_id").Value = Null.ReplaceNull(Value, DBNull.Value)
            End Set
        End Property

    End Class

End Class
